controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

delete_image:
    path: /delete-image
    controller: App\Controller\ProprietaireController::deleteImage
    methods: ['POST']
    
api_login_check:
    path: /api/login_check
    